package com.mycloudgallery.core.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "albums",
    indices = [Index("name")],
)
data class AlbumEntity(
    @PrimaryKey val id: String,
    val name: String,
    val coverMediaId: String?,
    val createdAt: Long,
    @ColumnInfo(defaultValue = "0") val isAutoGenerated: Boolean = false,
    @ColumnInfo(defaultValue = "0") val sortOrder: Int = 0,
)
