package com.mycloudgallery.core.util

import com.mycloudgallery.core.database.entity.AlbumEntity
import com.mycloudgallery.core.database.entity.MediaItemEntity
import com.mycloudgallery.domain.model.Album
import com.mycloudgallery.domain.model.MediaItem
import com.mycloudgallery.domain.model.MediaType
import kotlinx.serialization.json.Json

private val json = Json { ignoreUnknownKeys = true }

// --- MediaItem ---

fun MediaItemEntity.toDomain(): MediaItem = MediaItem(
    id = id,
    fileName = fileName,
    mimeType = mimeType,
    fileSize = fileSize,
    createdAt = createdAt,
    modifiedAt = modifiedAt,
    webDavPath = webDavPath,
    thumbnailCachePath = thumbnailCachePath,
    mediaType = if (isVideo) MediaType.VIDEO else MediaType.fromMimeType(mimeType),
    videoDuration = videoDuration,
    width = width,
    height = height,
    exifLatitude = exifLatitude,
    exifLongitude = exifLongitude,
    exifCameraModel = exifCameraModel,
    exifIso = exifIso,
    exifFocalLength = exifFocalLength,
    aiLabels = aiLabels?.parseJsonStringList().orEmpty(),
    aiScenes = aiScenes?.parseJsonStringList().orEmpty(),
    aiOcrText = aiOcrText,
    isIndexed = isIndexed,
    isInTrash = isInTrash,
    trashedAt = trashedAt,
    isFavorite = isFavorite,
)

fun MediaItem.toEntity(): MediaItemEntity = MediaItemEntity(
    id = id,
    fileName = fileName,
    mimeType = mimeType,
    fileSize = fileSize,
    createdAt = createdAt,
    modifiedAt = modifiedAt,
    webDavPath = webDavPath,
    thumbnailCachePath = thumbnailCachePath,
    isVideo = mediaType == MediaType.VIDEO,
    videoDuration = videoDuration,
    width = width,
    height = height,
    exifLatitude = exifLatitude,
    exifLongitude = exifLongitude,
    exifCameraModel = exifCameraModel,
    exifIso = exifIso,
    exifFocalLength = exifFocalLength,
    aiLabels = if (aiLabels.isNotEmpty()) aiLabels.toJsonString() else null,
    aiScenes = if (aiScenes.isNotEmpty()) aiScenes.toJsonString() else null,
    aiOcrText = aiOcrText,
    isIndexed = isIndexed,
    isInTrash = isInTrash,
    trashedAt = trashedAt,
    isFavorite = isFavorite,
)

// --- Album ---

fun AlbumEntity.toDomain(mediaCount: Int = 0): Album = Album(
    id = id,
    name = name,
    coverMediaId = coverMediaId,
    mediaCount = mediaCount,
    createdAt = createdAt,
    isAutoGenerated = isAutoGenerated,
    sortOrder = sortOrder,
)

fun Album.toEntity(): AlbumEntity = AlbumEntity(
    id = id,
    name = name,
    coverMediaId = coverMediaId,
    createdAt = createdAt,
    isAutoGenerated = isAutoGenerated,
    sortOrder = sortOrder,
)

// --- JSON helpers per liste di stringhe ---

private fun String.parseJsonStringList(): List<String> = try {
    json.decodeFromString<List<String>>(this)
} catch (_: Exception) {
    // Fallback: stringa CSV per compatibilità con dati legacy
    split(",").map { it.trim() }.filter { it.isNotBlank() }
}

private fun List<String>.toJsonString(): String =
    json.encodeToString(kotlinx.serialization.builtins.ListSerializer(kotlinx.serialization.builtins.serializer()), this)
