package com.mycloudgallery.data.repository

import com.mycloudgallery.core.database.dao.AlbumDao
import com.mycloudgallery.core.database.dao.AlbumWithCount
import com.mycloudgallery.core.database.dao.MediaItemDao
import com.mycloudgallery.core.database.entity.AlbumEntity
import com.mycloudgallery.core.database.entity.AlbumMediaCrossRef
import com.mycloudgallery.core.util.toDomain
import com.mycloudgallery.domain.model.Album
import com.mycloudgallery.domain.model.MediaItem
import com.mycloudgallery.domain.repository.AlbumRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AlbumRepositoryImpl @Inject constructor(
    private val albumDao: AlbumDao,
    private val mediaItemDao: MediaItemDao,
) : AlbumRepository {

    override fun getAll(): Flow<List<Album>> =
        albumDao.getAllWithCounts().map { list ->
            list.map { it.album.toDomain(mediaCount = it.mediaCount) }
        }

    override fun getMediaForAlbum(albumId: String): Flow<List<MediaItem>> =
        albumDao.getMediaForAlbum(albumId).map { entities ->
            entities.map { it.toDomain() }
        }

    override fun getFavoritesCount(): Flow<Int> =
        mediaItemDao.getFavoritesCount()

    override suspend fun createAlbum(name: String): Album {
        val entity = AlbumEntity(
            id = UUID.randomUUID().toString(),
            name = name.trim(),
            coverMediaId = null,
            createdAt = System.currentTimeMillis(),
            isAutoGenerated = false,
            sortOrder = 0,
        )
        albumDao.insert(entity)
        return entity.toDomain()
    }

    override suspend fun renameAlbum(id: String, newName: String) {
        val entity = albumDao.getById(id)
            ?: throw IllegalArgumentException("Album $id non trovato")
        require(!entity.isAutoGenerated) { "Gli album auto-generati non possono essere rinominati" }
        albumDao.update(entity.copy(name = newName.trim()))
    }

    override suspend fun deleteAlbum(id: String) {
        val entity = albumDao.getById(id)
            ?: throw IllegalArgumentException("Album $id non trovato")
        require(!entity.isAutoGenerated) { "Gli album auto-generati non possono essere eliminati" }
        albumDao.deleteById(id)
        // AlbumMediaCrossRef eliminati automaticamente per CASCADE
    }

    override suspend fun addMediaToAlbum(albumId: String, mediaIds: List<String>) {
        val crossRefs = mediaIds.map { mediaId ->
            AlbumMediaCrossRef(albumId = albumId, mediaItemId = mediaId)
        }
        albumDao.addMediaToAlbumBatch(crossRefs)

        // Imposta la cover con il primo media inserito se l'album non ne ha ancora una
        val album = albumDao.getById(albumId)
        if (album != null && album.coverMediaId == null && mediaIds.isNotEmpty()) {
            albumDao.update(album.copy(coverMediaId = mediaIds.first()))
        }
    }

    override suspend fun removeMediaFromAlbum(albumId: String, mediaIds: List<String>) {
        albumDao.removeMediaFromAlbumBatch(albumId, mediaIds)
    }

    override suspend fun updateSortOrder(id: String, newSortOrder: Int) {
        val entity = albumDao.getById(id) ?: return
        albumDao.update(entity.copy(sortOrder = newSortOrder))
    }

    override suspend fun updateCover(albumId: String, mediaId: String) {
        val entity = albumDao.getById(albumId) ?: return
        albumDao.update(entity.copy(coverMediaId = mediaId))
    }
}
