package com.mycloudgallery.data.repository

import com.mycloudgallery.core.database.dao.AlbumDao
import com.mycloudgallery.core.database.dao.MediaItemDao
import com.mycloudgallery.core.database.entity.AlbumEntity
import com.mycloudgallery.core.database.entity.AlbumMediaCrossRef
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class AlbumRepositoryTest {

    private lateinit var albumDao: AlbumDao
    private lateinit var mediaItemDao: MediaItemDao
    private lateinit var repository: AlbumRepositoryImpl

    @BeforeEach
    fun setUp() {
        albumDao = mockk(relaxed = true)
        mediaItemDao = mockk(relaxed = true)
        every { mediaItemDao.getFavoritesCount() } returns flowOf(0)
        repository = AlbumRepositoryImpl(albumDao, mediaItemDao)
    }

    @Test
    fun `createAlbum genera UUID e inserisce nel DAO`() = runTest {
        val capturedEntity = slot<AlbumEntity>()
        coEvery { albumDao.insert(capture(capturedEntity)) } returns Unit

        val result = repository.createAlbum("Vacanze 2025")

        assertEquals("Vacanze 2025", result.name)
        assertNotNull(result.id)
        coVerify { albumDao.insert(any()) }
        assertEquals("Vacanze 2025", capturedEntity.captured.name)
    }

    @Test
    fun `createAlbum rimuove spazi iniziali e finali dal nome`() = runTest {
        val capturedEntity = slot<AlbumEntity>()
        coEvery { albumDao.insert(capture(capturedEntity)) } returns Unit

        repository.createAlbum("  Album con spazi  ")

        assertEquals("Album con spazi", capturedEntity.captured.name)
    }

    @Test
    fun `renameAlbum aggiorna il nome nel DAO`() = runTest {
        val existing = AlbumEntity("id1", "Vecchio nome", null, 1000L, false, 0)
        coEvery { albumDao.getById("id1") } returns existing

        repository.renameAlbum("id1", "Nuovo nome")

        coVerify { albumDao.update(existing.copy(name = "Nuovo nome")) }
    }

    @Test
    fun `renameAlbum lancia eccezione se album non esiste`() = runTest {
        coEvery { albumDao.getById("nonexistent") } returns null

        assertThrows(IllegalArgumentException::class.java) {
            runTest { repository.renameAlbum("nonexistent", "Nome") }
        }
    }

    @Test
    fun `renameAlbum lancia eccezione per album auto-generato`() = runTest {
        val autoAlbum = AlbumEntity("auto", "Preferiti", null, 1000L, isAutoGenerated = true, 0)
        coEvery { albumDao.getById("auto") } returns autoAlbum

        assertThrows(IllegalArgumentException::class.java) {
            runTest { repository.renameAlbum("auto", "Altro nome") }
        }
    }

    @Test
    fun `deleteAlbum lancia eccezione per album auto-generato`() = runTest {
        val autoAlbum = AlbumEntity("auto", "Preferiti", null, 1000L, isAutoGenerated = true, 0)
        coEvery { albumDao.getById("auto") } returns autoAlbum

        assertThrows(IllegalArgumentException::class.java) {
            runTest { repository.deleteAlbum("auto") }
        }
    }

    @Test
    fun `addMediaToAlbum aggiunge batch di cross-ref e imposta cover se assente`() = runTest {
        val album = AlbumEntity("a1", "Test", null, 1000L, false, 0)
        coEvery { albumDao.getById("a1") } returns album
        val capturedBatch = slot<List<AlbumMediaCrossRef>>()
        coEvery { albumDao.addMediaToAlbumBatch(capture(capturedBatch)) } returns Unit

        repository.addMediaToAlbum("a1", listOf("m1", "m2", "m3"))

        assertEquals(3, capturedBatch.captured.size)
        assertEquals("a1", capturedBatch.captured[0].albumId)
        // Cover impostata al primo media poiché era null
        coVerify { albumDao.update(album.copy(coverMediaId = "m1")) }
    }

    @Test
    fun `addMediaToAlbum non sovrascrive cover esistente`() = runTest {
        val album = AlbumEntity("a1", "Test", coverMediaId = "existing", 1000L, false, 0)
        coEvery { albumDao.getById("a1") } returns album
        coEvery { albumDao.addMediaToAlbumBatch(any()) } returns Unit

        repository.addMediaToAlbum("a1", listOf("m1"))

        // update non chiamato per la cover
        coVerify(exactly = 0) { albumDao.update(any()) }
    }
}
