package com.mycloudgallery.domain.model

data class Album(
    val id: String,
    val name: String,
    val coverMediaId: String?,
    val mediaCount: Int,
    val createdAt: Long,
    val isAutoGenerated: Boolean,
    val sortOrder: Int,
)
